import {strict as a} from 'node:assert';
import {waterParams,waveHeight,mediumAt,waterPath,swimStep} from '../../shared/water.js';
const water={...waterParams({center:[0,-10,0],size:[100,20,100]}),top:0,bottom:-20};
const box={center:[0,-5,0],size:[4,4,4]};
a.equal(mediumAt([0,2,0],[water],[]),null);
a.equal(mediumAt([70,-5,0],[water],[]),null);
a.equal(mediumAt([0,-5,0],[water],[box]),null);
a.equal(mediumAt([4,-5,0],[water],[box]),water);
a.equal(waterPath([-10,-5,0],[10,-5,0],water,[box,box]),16);
a.equal(waterPath([0,-5,0],[1,-5,0],water,[box]),0);
a.equal(waterPath([0,10,0],[0,-10,0],water,[]),10);
a.equal(waterPath([0,-5,0],[0,-5,0],water,[]),0);
a.ok(Math.abs(waterPath([-10,-5,0],[10,-5,0],water,[box,{center:[2,-5,0],size:[4,4,4]}])-14)<1e-9);
a.equal(waterPath([-10,-5,0],[10,-5,0],water,[box,{center:[0,-5,0],size:[2,2,2]}]),16);
const rotated={center:[0,-5,0],size:[8,2,2],toLocal:p=>[p[2],p[1]+5,-p[0]]};
a.equal(mediumAt([0,-5,3],[water],[rotated]),null);
a.equal(waterPath([-10,-5,0],[10,-5,0],water,[rotated]),18);
let s={pos:[0,-4,0],velocity:[0,0,0]};
for(let i=0;i<300;i++)s=swimStep(s.pos,s.velocity,{direction:[0,1,0],rise:true},water,1/60,i/60);
a.equal(s.mode,'surface');a.ok(Math.abs(s.pos[1]+1.1)<1e-8);
for(let i=0;i<60;i++)s=swimStep(s.pos,s.velocity,{direction:[0,-1,0],dive:true},water,1/60,i/60);
a.ok(s.pos[1]<-2);a.equal(s.mode,'swim');
const w={...water,waves:[{amplitude:.4,wavelength:10,direction:[1,0],phase:Math.PI/2}]};
a.ok(Math.abs(waveHeight(w,0,0,0)-.4)<1e-10);
const bad=waterParams({size:[NaN,0,Infinity],waves:[null],absorption:[NaN,0,1]});
a.ok(bad.size.every(Number.isFinite));a.ok(bad.absorption.every(Number.isFinite));
console.log('PASS: wet/dry boundaries, surface crossings, zero/parallel rays, nested/overlapping/rotated air volumes, ascent, surface latch, diving, waves, malformed data');
